### ISSUE TITLE
Gallery 'full path' link

### ISSUE THREAD

**Issue by melanierogan** [Financial-Times/email-meme-frontend#344]
When we upload an image to the gallery, can there be a quick copy link to copy the full path of the image so we can place this in the html code.

**Comment by syymza** [comment]
You can right-click at any time on an image and get its path clicking on "Copy Image Address" (on Chrome). Anyway, we advise to use the image picker (now available also for html snippets) because we proxy the image in that case (resizing and putting a CDN in front of it), which guarantees better performance.

**Comment by melanierogan** [comment]
I think you can mark this as resolved, you're right, image picker clears this being an issue.
